# Generated by Django 2.2.3 on 2019-08-12 17:20

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='after_image',
            field=models.FileField(default='after_image.jpg', upload_to=main.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='post',
            name='before_image',
            field=models.FileField(default='before_image.jpg', upload_to=main.models.user_directory_path),
        ),
    ]
