# Generated by Django 2.1.9 on 2019-08-13 18:30

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190813_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='after_image',
            field=models.ImageField(default='after_image.jpg', upload_to=main.models.user_directory_path),
        ),
    ]
