# Generated by Django 2.1.9 on 2019-08-14 23:00

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_post_after_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='after_image',
            field=models.FileField(blank=True, default='after_image.jpg', upload_to=main.models.user_directory_path),
        ),
    ]
