# Generated by Django 2.2.3 on 2019-08-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics_1'),
        ),
        migrations.AddField(
            model_name='profile',
            name='second_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics_2'),
        ),
        migrations.AddField(
            model_name='profile',
            name='third_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics_3'),
        ),
    ]
